apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc }}
