apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "api-gateway.fullname" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
  type: ClusterIP
