apiVersion: apps/v1
kind: Deployment
metadata:
  name: zar-api-gateway
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zar-api-gateway
  template:
    metadata:
      labels:
        app: zar-api-gateway
    spec:
      containers:
      - name: zar-api-gateway
        image: aliquis21/zar-api-gateway-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:               # Лимиты ресурсов
            memory: "512Mi"      # Максимум 512Mi памяти
            cpu: "500m"          # Максимум 500m CPU
          requests:              # Запросы ресурсов
            memory: "256Mi"      # Запрашивается 256Mi памяти
            cpu: "250m"          # Запрашивается 250m CPU
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zar-api-gateway-service-secrets
              key: DATABASE_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: zar-api-gateway-service-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: JWT_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: zar-api-gateway-service-config
              key: JWT_SECRET_KEY
      imagePullSecrets:
        - name: regcred
