CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "password" varchar(100) NOT NULL,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "account" float DEFAULT 0,
  "face_vector" json,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Account" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "account_name" varchar(50) NOT NULL,
  "balance" float DEFAULT 0,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Transaction" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int,
  "amount" float NOT NULL,
  "type" varchar(10) NOT NULL,
  "transaction_date" timestamp DEFAULT (now()),
  "description" varchar(255)
);

CREATE TABLE "Report" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "generated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Transaction_Report" (
  "transaction_id" int,
  "report_id" int
);

ALTER TABLE "Account" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Transaction" ADD FOREIGN KEY ("account_id") REFERENCES "Account" ("id");

ALTER TABLE "Report" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Transaction_Report" ADD FOREIGN KEY ("transaction_id") REFERENCES "Transaction" ("id");

ALTER TABLE "Transaction_Report" ADD FOREIGN KEY ("report_id") REFERENCES "Report" ("id");
